version: '3.8'
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: qme_app
    working_dir: /var/www
    volumes:
      - ./qme:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: qme_nginx
    ports:
      - "8080:80"
    volumes:
      - ./qme:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:8.0
    container_name: qme_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: qme
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
